dist: xenial
language: python
python:
  - "3.7.1"


env:
  global:
    - IDFY_MOCK_SERVER_VERSION=0.0.3

before_install:
  # Download, unpack and run the Idfy Mock Server
  - |
    wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt-get install apt-transport-https
    sudo apt-get update
    sudo apt-get install aspnetcore-runtime-2.2
    mkdir -p idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/
    curl -L "https://github.com/idfy-io/idfy-mock-server/releases/download/v${IDFY_MOCK_SERVER_VERSION}/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -o "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip"
    unzip "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}.zip" -d "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/"
    dotnet "idfy-mock-server/idfy-mock-server_${IDFY_MOCK_SERVER_VERSION}/Idfy.MockServer.dll" &
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --upgrade setuptools wheel
  - python3 setup.py sdist bdist_wheel

script:
  - python3 -m unittest

deploy:
  # Create GitHub release on new version
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    name: $TRAVIS_TAG
    on:
      tags: true
  # Push NuGet package to nuget.org on new version
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true

notifications:
  slack:
    secure: Evp+mLf0LJJ7NL7hPirJPFC+gBP//6X11r+J3mrUBlmW5LRzxoKUnEyfZCMo+8zPdchGArvNVSD0SdCHSAwHKyx/u/CDPj2y+6c5MF+eTQZF7N4KEdKJykElkzZPOjWufbgnuaZtjvTQYmGsl5Lw7W4ZBGKWfJSKsfVZJmSafFLGk9PHaI+Ote8Dg+yxX7HaxwcZQp9npyZs3HA1l5m6xCUV+YZ+B0f8Ctw0QHrnDk8pw6W246AmqND5j/Y1Wvh9opx94DvHc0oWdY8uPW3sVBJOA0sIopvd2NqbyzkfjTKT2fHPRL4T/O9F3f/oiE1CmeVY+rKKDFrJkbGV6mdxDxYdYGx9uU0JsKvYYudG4TRZcKB4zJDT8izG9yIA6tx+dkS04+QeiExw4WiZcDPdojv/X/iZVW23UDLGasMvNzHBmtOKVWtCXQ21a+6mkRvpbxFBFqo7dz5fVpiCH1tPcwiHOAfhZ8J/Jd3k9qcnUkq3G5/8Q9Cjwb7JezQFAJUIVBtD1GIpcw4ZsHiUUrLvXqMdnMJsidlIFYgQO3eL4apdFA0s799X7iZ3I7FKy0iqsULweU1rwMZusc9Hhdmx4M4xuV5gU9wcC/Matsk+U6LSIJHgaliG5Qvcj2t/xuF08XACkCKcnypJTpNHk1YAZfbNM7gT24ycvI6nIJdlrSk=
    on_failure: always
    on_success: change